#!/bin/bash

# Define the file name with proper escaping
file_name='\*\\\'"Best School"\''\'\\*\$\?\*\*\*\*\*:)''                                                            
printf "Best School\n" > "$file_name"                                                           
echo "File '$file_name' created"
